language: bash
dist: xenial

language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install pylint virtualenv"
# command to build
script: 
  - ./dev build
  - ./dev release
  - ./dev tests
